# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TaskResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, state: str=None, end_date: str=None, begin_date: str=None):  # noqa: E501
        """TaskResponse - a model defined in Swagger

        :param id: The id of this TaskResponse.  # noqa: E501
        :type id: str
        :param name: The name of this TaskResponse.  # noqa: E501
        :type name: str
        :param state: The state of this TaskResponse.  # noqa: E501
        :type state: str
        :param end_date: The end_date of this TaskResponse.  # noqa: E501
        :type end_date: str
        :param begin_date: The begin_date of this TaskResponse.  # noqa: E501
        :type begin_date: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'state': str,
            'end_date': str,
            'begin_date': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'state': 'state',
            'end_date': 'end_date',
            'begin_date': 'begin_date'
        }
        self._id = id
        self._name = name
        self._state = state
        self._end_date = end_date
        self._begin_date = begin_date

    @classmethod
    def from_dict(cls, dikt) -> 'TaskResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskResponse of this TaskResponse.  # noqa: E501
        :rtype: TaskResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this TaskResponse.


        :return: The id of this TaskResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TaskResponse.


        :param id: The id of this TaskResponse.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this TaskResponse.


        :return: The name of this TaskResponse.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TaskResponse.


        :param name: The name of this TaskResponse.
        :type name: str
        """

        self._name = name

    @property
    def state(self) -> str:
        """Gets the state of this TaskResponse.


        :return: The state of this TaskResponse.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this TaskResponse.


        :param state: The state of this TaskResponse.
        :type state: str
        """

        self._state = state

    @property
    def end_date(self) -> str:
        """Gets the end_date of this TaskResponse.


        :return: The end_date of this TaskResponse.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: str):
        """Sets the end_date of this TaskResponse.


        :param end_date: The end_date of this TaskResponse.
        :type end_date: str
        """

        self._end_date = end_date

    @property
    def begin_date(self) -> str:
        """Gets the begin_date of this TaskResponse.


        :return: The begin_date of this TaskResponse.
        :rtype: str
        """
        return self._begin_date

    @begin_date.setter
    def begin_date(self, begin_date: str):
        """Sets the begin_date of this TaskResponse.


        :param begin_date: The begin_date of this TaskResponse.
        :type begin_date: str
        """

        self._begin_date = begin_date
